# netlify.toml

[build]
  command   = "npm run build"
  publish   = "build"

[[redirects]]
  from     = "/detect"
  to       = "https://e471-136-158-123-1.ngrok-free.app/detect"
  status   = 200
  force    = true
  methods  = ["POST"]

[[redirects]]
  from     = "/video_feed"
  to       = "https://e471-136-158-123-1.ngrok-free.app/video_feed"
  status   = 200
  force    = true
  methods  = ["GET"]

[[redirects]]
  from     = "/*"
  to       = "/index.html"
  status   = 200
